.PHONY: clean All

All:
	@echo "----------Building project:[ BankManagementSystemGui - Debug ]----------"
	@cd "BankManagementSystemGui" && "$(MAKE)" -f  "BankManagementSystemGui.mk"
clean:
	@echo "----------Cleaning project:[ BankManagementSystemGui - Debug ]----------"
	@cd "BankManagementSystemGui" && "$(MAKE)" -f  "BankManagementSystemGui.mk" clean
