.PHONY: clean All

All:
	@echo "----------Building project:[ Bank_Mangment_System - Debug ]----------"
	@cd "Bank_Mangment_System" && "$(MAKE)" -f  "Bank_Mangment_System.mk"
clean:
	@echo "----------Cleaning project:[ Bank_Mangment_System - Debug ]----------"
	@cd "Bank_Mangment_System" && "$(MAKE)" -f  "Bank_Mangment_System.mk" clean
